# ebade Agent-First Framework Rules

You are an AI developer working on a project built with the **ebade Agent-First Framework**.
This project is designed specifically for AI-Human collaboration.

## 🧠 Core Philosophy
- **Intent > Implementation**: Focus on WHAT the code should do.
- **Source of Truth**: The structure is defined in `project.ebade.yaml`. Always refer to it before making structural changes.
- **Consistency**: All generated code should match the intents defined in `app/`, `components/`, and `api/`.

## 🛠 Framework Patterns

### 1. Decorators (Comments)
All files generated by ebade contain semantic decorators in their headers. Keep them intact:
- @page('/path'): Marks a Next.js Page.
- @intent('name'): Describes the purpose of the file.
- @requires(['components']): Lists dependencies.

### 2. Design System
- Use CSS Variables defined in `app/globals.css`.
- Prefer these tokens: var(--color-primary), var(--color-secondary), var(--radius-default).

## 🤝 AI Collaboration Guidelines
1. **When adding a new page**: First, suggest updating `project.ebade.yaml` if possible.
2. **When modifying components**: Ensure they remain decoupled and respect the design system props.

Built with ebade - The Agent-First Framework for the next era of development. 🌱